// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDgs_9ToiVctEcPE0V9VpI65chCWOxkF3Y',
    appId: '1:722794541286:web:d0837472e103a074104b27',
    messagingSenderId: '722794541286',
    projectId: 'flutterfirebase2324',
    authDomain: 'flutterfirebase2324.firebaseapp.com',
    storageBucket: 'flutterfirebase2324.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCcKTEnDWUn1l1ttZlEmKlYgBu6kruSG-o',
    appId: '1:722794541286:android:7dcfd03c2058f39e104b27',
    messagingSenderId: '722794541286',
    projectId: 'flutterfirebase2324',
    storageBucket: 'flutterfirebase2324.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUzrKY6xTmC8_Dhle_77WPAXTfk4AWRkE',
    appId: '1:722794541286:ios:b1fcf354ded5ba54104b27',
    messagingSenderId: '722794541286',
    projectId: 'flutterfirebase2324',
    storageBucket: 'flutterfirebase2324.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUzrKY6xTmC8_Dhle_77WPAXTfk4AWRkE',
    appId: '1:722794541286:ios:88d3bbf6f423f376104b27',
    messagingSenderId: '722794541286',
    projectId: 'flutterfirebase2324',
    storageBucket: 'flutterfirebase2324.appspot.com',
    iosBundleId: 'com.example.flutterFirebase2324.RunnerTests',
  );
}